extern const GeoLayout castle_courtyard_area_1_geo[];
extern const GeoLayout castle_courtyard_area_1[];
extern const Collision castle_courtyard_area_1_collision[];
extern const MacroObject castle_courtyard_area_1_macro_objs[];
extern u8 castle_courtyard_dl_RMGP01_f2886623_14_mip1_i4[];
extern u8 castle_courtyard_dl_cs_lawn06_alb_rgba16[];
extern Vtx castle_courtyard_dl__Hub__001_mesh_layer_1_vtx_0[4];
extern Gfx castle_courtyard_dl__Hub__001_mesh_layer_1_tri_0[];
extern Gfx mat_castle_courtyard_dl_grass_layer1[];
extern Gfx mat_revert_castle_courtyard_dl_grass_layer1[];
extern Gfx castle_courtyard_dl__Hub__001_mesh_layer_1[];
