extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_RMGP01_f2886623_14_mip1_i8[];
extern Vtx castle_grounds_dl__Hub__mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl__Hub__mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_grass[];
extern Gfx mat_revert_castle_grounds_dl_grass[];
extern Gfx castle_grounds_dl__Hub__mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
