extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern const GeoLayout bob_area_4_geo[];
extern const GeoLayout bob_area_4[];
extern const Collision bob_area_4_collision[];
extern const MacroObject bob_area_4_macro_objs[];
extern const GeoLayout bob_area_5_geo[];
extern const GeoLayout bob_area_5[];
extern const Collision bob_area_5_collision[];
extern const MacroObject bob_area_5_macro_objs[];
extern Lights1 bob_dl_minecart_metal_lights;
extern Lights1 bob_dl_minecart_wood_lights;
extern u8 bob_dl_tempImgEd001A_i8[];
extern u8 bob_dl_ci4_nat_carpet_spades_i8[];
extern u8 bob_dl_pumpkin_i8[];
extern u8 bob_dl_ci4_nat_metal2_i8[];
extern u8 bob_dl_RMGP01_f2886623_14_mip1_i4[];
extern u8 bob_dl_Glover_D3595F8B_0_0_6C714BED_ciByRGBA_rgba16[];
extern u8 bob_dl_TexturSMG__189__rgba16[];
extern u8 bob_dl_i4_pyrojay_clouds1_i4[];
extern u8 bob_dl_Rock_kh02_spc_i8[];
extern u8 bob_dl_ACMTRKF1_ia8[];
extern u8 bob_dl_Leitplank2_ia8[];
extern u8 bob_dl_fancywater3_ia8[];
extern u8 bob_dl_rgba16_anonmoose_GrungyMetal3_rgba16[];
extern u8 bob_dl_Bruecke_rgba16[];
extern u8 bob_dl_ci4_nat_lava__2__ci4[];
extern u8 bob_dl_ci4_nat_lava__2__x_ci4_nat_lava__2__pal_rgba16[];
extern u8 bob_dl_ci4_nat_lava__2__ci4_copy[];
extern u8 bob_dl_i4_zeina_cobblestone_1_ia4[];
extern u8 bob_dl_KKIIDDZZ_DAT_775__p00_ia8[];
extern u8 bob_dl_KKIIDDZZ_DAT_1183__p00_ia8[];
extern u8 bob_dl_spider_eyes_rgba16[];
extern u8 bob_dl_ci4_nat_lava_i8[];
extern u8 bob_dl_ci4_nat_plastic_i8[];
extern u8 bob_dl_i4_zeina_stone_bricks_1_i4[];
extern u8 bob_dl_RMGP01_9092fc13_14_i8[];
extern u8 bob_dl_D61220C2810ABF78D9AF9C7DBF9760B8_i8[];
extern u8 bob_dl_rgba16_anonmoose_envmap_gold2_ci4[];
extern u8 bob_dl_rgba16_anonmoose_envmap_gold2_pal_rgba16[];
extern Vtx bob_dl__Spades_mesh_layer_1_vtx_0[57];
extern Gfx bob_dl__Spades_mesh_layer_1_tri_0[];
extern Vtx bob_dl__Spades_mesh_layer_1_vtx_1[267];
extern Gfx bob_dl__Spades_mesh_layer_1_tri_1[];
extern Vtx bob_dl__Jack_O_Lantern_mesh_layer_1_vtx_0[176];
extern Gfx bob_dl__Jack_O_Lantern_mesh_layer_1_tri_0[];
extern Vtx bob_dl__Jack_O_Lantern_mesh_layer_1_vtx_1[130];
extern Gfx bob_dl__Jack_O_Lantern_mesh_layer_1_tri_1[];
extern Vtx bob_dl__Jack_O_Lantern_mesh_layer_1_vtx_2[183];
extern Gfx bob_dl__Jack_O_Lantern_mesh_layer_1_tri_2[];
extern Vtx bob_dl__Jack_O_Lantern_Visual_mesh_layer_1_vtx_0[185];
extern Gfx bob_dl__Jack_O_Lantern_Visual_mesh_layer_1_tri_0[];
extern Vtx bob_dl__Jack_O_Lantern_Visual_mesh_layer_1_vtx_1[2551];
extern Gfx bob_dl__Jack_O_Lantern_Visual_mesh_layer_1_tri_1[];
extern Vtx bob_dl__Jack_O_Lantern_Visual_mesh_layer_1_vtx_2[373];
extern Gfx bob_dl__Jack_O_Lantern_Visual_mesh_layer_1_tri_2[];
extern Vtx bob_dl__Jack_O_Lantern_Visual_mesh_layer_1_vtx_3[284];
extern Gfx bob_dl__Jack_O_Lantern_Visual_mesh_layer_1_tri_3[];
extern Vtx bob_dl__Skull_mesh_layer_1_vtx_0[149];
extern Gfx bob_dl__Skull_mesh_layer_1_tri_0[];
extern Vtx bob_dl__Skull_mesh_layer_1_vtx_1[291];
extern Gfx bob_dl__Skull_mesh_layer_1_tri_1[];
extern Vtx bob_dl__Skull_Visual_mesh_layer_1_vtx_0[302];
extern Gfx bob_dl__Skull_Visual_mesh_layer_1_tri_0[];
extern Vtx bob_dl__Skull_Visual_mesh_layer_1_vtx_1[1983];
extern Gfx bob_dl__Skull_Visual_mesh_layer_1_tri_1[];
extern Vtx bob_dl__Skull_Visual_mesh_layer_1_vtx_2[1042];
extern Gfx bob_dl__Skull_Visual_mesh_layer_1_tri_2[];
extern Vtx bob_dl__Skull_Visual_mesh_layer_6_vtx_0[8];
extern Gfx bob_dl__Skull_Visual_mesh_layer_6_tri_0[];
extern Vtx bob_dl__Skull_Visual_mesh_layer_5_vtx_0[13];
extern Gfx bob_dl__Skull_Visual_mesh_layer_5_tri_0[];
extern Vtx bob_dl__Skull_Visual_mesh_layer_5_vtx_1[4];
extern Gfx bob_dl__Skull_Visual_mesh_layer_5_tri_1[];
extern Vtx bob_dl_Skeleton_Dorrie_mesh_layer_1_vtx_0[1075];
extern Gfx bob_dl_Skeleton_Dorrie_mesh_layer_1_tri_0[];
extern Vtx bob_dl__Spider_mesh_layer_1_vtx_0[254];
extern Gfx bob_dl__Spider_mesh_layer_1_tri_0[];
extern Vtx bob_dl__Spider_mesh_layer_1_vtx_1[989];
extern Gfx bob_dl__Spider_mesh_layer_1_tri_1[];
extern Vtx bob_dl__Spider_Visual_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl__Spider_Visual_mesh_layer_5_tri_0[];
extern Vtx bob_dl__Spider_Visual_mesh_layer_1_vtx_0[343];
extern Gfx bob_dl__Spider_Visual_mesh_layer_1_tri_0[];
extern Vtx bob_dl__Spider_Visual_mesh_layer_4_vtx_0[16];
extern Gfx bob_dl__Spider_Visual_mesh_layer_4_tri_0[];
extern Vtx bob_dl__Spider_Visual_mesh_layer_4_vtx_1[30];
extern Gfx bob_dl__Spider_Visual_mesh_layer_4_tri_1[];
extern Vtx bob_dl__Spider_Visual_mesh_layer_4_vtx_2[20];
extern Gfx bob_dl__Spider_Visual_mesh_layer_4_tri_2[];
extern Vtx bob_dl__Pizza_mesh_layer_1_vtx_0[148];
extern Gfx bob_dl__Pizza_mesh_layer_1_tri_0[];
extern Vtx bob_dl__Pizza_mesh_layer_1_vtx_1[88];
extern Gfx bob_dl__Pizza_mesh_layer_1_tri_1[];
extern Vtx bob_dl__Pizza_mesh_layer_1_vtx_2[77];
extern Gfx bob_dl__Pizza_mesh_layer_1_tri_2[];
extern Vtx bob_dl__Pizza_Visual_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl__Pizza_Visual_mesh_layer_1_tri_0[];
extern Vtx bob_dl__Pizza_Visual_mesh_layer_1_vtx_1[887];
extern Gfx bob_dl__Pizza_Visual_mesh_layer_1_tri_1[];
extern Vtx bob_dl__Pizza_Visual_mesh_layer_1_vtx_2[57];
extern Gfx bob_dl__Pizza_Visual_mesh_layer_1_tri_2[];
extern Vtx bob_dl__Pizza_Visual_mesh_layer_1_vtx_3[28];
extern Gfx bob_dl__Pizza_Visual_mesh_layer_1_tri_3[];
extern Vtx bob_dl__Pizza_Visual_mesh_layer_1_vtx_4[151];
extern Gfx bob_dl__Pizza_Visual_mesh_layer_1_tri_4[];
extern Gfx mat_bob_dl_sand[];
extern Gfx mat_revert_bob_dl_sand[];
extern Gfx mat_bob_dl_black[];
extern Gfx mat_revert_bob_dl_black[];
extern Gfx mat_bob_dl_pumpkin[];
extern Gfx mat_revert_bob_dl_pumpkin[];
extern Gfx mat_bob_dl_barrier[];
extern Gfx mat_revert_bob_dl_barrier[];
extern Gfx mat_bob_dl_grass_3[];
extern Gfx mat_revert_bob_dl_grass_3[];
extern Gfx mat_bob_dl_pumpkin_stem[];
extern Gfx mat_revert_bob_dl_pumpkin_stem[];
extern Gfx mat_bob_dl_jack_o_lantern_light[];
extern Gfx mat_bob_dl_bone[];
extern Gfx mat_revert_bob_dl_bone[];
extern Gfx mat_bob_dl_stone[];
extern Gfx mat_revert_bob_dl_stone[];
extern Gfx mat_bob_dl_rails[];
extern Gfx mat_revert_bob_dl_rails[];
extern Gfx mat_bob_dl_fence[];
extern Gfx mat_revert_bob_dl_fence[];
extern Gfx mat_bob_dl_water_2[];
extern Gfx mat_revert_bob_dl_water_2[];
extern Gfx mat_bob_dl_minecart_metal[];
extern Gfx mat_bob_dl_minecart_wood[];
extern Gfx mat_bob_dl_lava_2[];
extern Gfx mat_revert_bob_dl_lava_2[];
extern Gfx mat_bob_dl_cobblestone[];
extern Gfx mat_revert_bob_dl_cobblestone[];
extern Gfx mat_bob_dl_cobweb[];
extern Gfx mat_revert_bob_dl_cobweb[];
extern Gfx mat_bob_dl_cobweb_big[];
extern Gfx mat_revert_bob_dl_cobweb_big[];
extern Gfx mat_bob_dl_spider_eyes[];
extern Gfx mat_revert_bob_dl_spider_eyes[];
extern Gfx mat_bob_dl_lava[];
extern Gfx mat_revert_bob_dl_lava[];
extern Gfx mat_bob_dl_plastic[];
extern Gfx mat_revert_bob_dl_plastic[];
extern Gfx mat_bob_dl_fancy_cloud_layer1[];
extern Gfx mat_revert_bob_dl_fancy_cloud_layer1[];
extern Gfx mat_bob_dl_tower_bricks[];
extern Gfx mat_revert_bob_dl_tower_bricks[];
extern Gfx mat_bob_dl_church_bricks[];
extern Gfx mat_revert_bob_dl_church_bricks[];
extern Gfx mat_bob_dl_church_roof[];
extern Gfx mat_revert_bob_dl_church_roof[];
extern Gfx mat_bob_dl_cross_gold[];
extern Gfx mat_revert_bob_dl_cross_gold[];
extern Gfx bob_dl__Spades_mesh_layer_1[];
extern Gfx bob_dl__Jack_O_Lantern_mesh_layer_1[];
extern Gfx bob_dl__Jack_O_Lantern_Visual_mesh_layer_1[];
extern Gfx bob_dl__Skull_mesh_layer_1[];
extern Gfx bob_dl__Skull_Visual_mesh_layer_1[];
extern Gfx bob_dl__Skull_Visual_mesh_layer_6[];
extern Gfx bob_dl__Skull_Visual_mesh_layer_5[];
extern Gfx bob_dl_Skeleton_Dorrie_mesh_layer_1[];
extern Gfx bob_dl__Spider_mesh_layer_1[];
extern Gfx bob_dl__Spider_Visual_mesh_layer_5[];
extern Gfx bob_dl__Spider_Visual_mesh_layer_1[];
extern Gfx bob_dl__Spider_Visual_mesh_layer_4[];
extern Gfx bob_dl__Pizza_mesh_layer_1[];
extern Gfx bob_dl__Pizza_Visual_mesh_layer_1[];
