extern const GeoLayout silver_star_geo[];
extern Lights1 Silver_Star_f3dlite_material_001_lights;
extern u8 Silver_Star_star_surface_rgba16_rgba16[];
extern u8 Silver_Star_star_eye_rgba16_rgba16[];
extern Vtx Silver_Star_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx Silver_Star_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx Silver_Star_001_displaylist_mesh_layer_5_vtx_0[8];
extern Gfx Silver_Star_001_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_Silver_Star_f3dlite_material[];
extern Gfx mat_revert_Silver_Star_f3dlite_material[];
extern Gfx mat_Silver_Star_f3dlite_material_001[];
extern Gfx mat_revert_Silver_Star_f3dlite_material_001[];
extern Gfx Silver_Star_000_displaylist_mesh_layer_1[];
extern Gfx Silver_Star_001_displaylist_mesh_layer_5[];
extern Gfx Silver_Star_material_revert_render_settings[];
