extern const GeoLayout star_geo[];
extern u8 star_star_eye_rgba16_i8[];
extern Vtx star_000_displaylist_mesh_layer_1_vtx_0[180];
extern Gfx star_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx star_001_displaylist_mesh_layer_5_vtx_0[8];
extern Gfx star_001_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_star_star[];
extern Gfx mat_star_f3dlite_material_003[];
extern Gfx mat_revert_star_f3dlite_material_003[];
extern Gfx star_000_displaylist_mesh_layer_1[];
extern Gfx star_001_displaylist_mesh_layer_5[];
extern Gfx star_material_revert_render_settings[];
